### PR TITLE
Removed obsolete filter and updated bootstrap.php

### LINKED ISSUE #176: Remove obsolete filter
https://github.com/Yoast/wpseo-news/blob/trunk/wpseo-news.php#L105-L106

Please also check where this is used in other plugins of ours.

### PR DESCRIPTION
**Pull request by jcomack**
Added missing WP_PLUGIN_DIR check in bootstrap.php and removed an obsolete wpseo_admin_pages filter. Fixes #176

### CODE REVIEW

**Comment by atimmer** [comment]
Shouldn't we also deprecated the function that would have been called on this filter. The method isn't called anywhere else as far as I can see.

**Comment by atimmer** [comment]
CR1 Done.

**Comment by andizer** [comment]
CR 2 Done :+1:

**Comment by andizer** [comment]
Acceptance done :+1:

**Pull request merged**
