### PR TITLE
wpseo_admin_pages is no longer being used in Yoast SEO. So it can be removed

### PR DESCRIPTION
**Pull request by diedexx**
related to https://github.com/Yoast/wordpress-seo-local/issues/458#issuecomment-188829155
Just like in Local SEO, this filter is no longer relevant.

### CODE REVIEW

**Comment by jcomack** [comment]
CR done

**Comment by terw-dan** [comment]
Since there is an error in news with a 404 on admin-page.min.js this issue is blocked.

**Comment by diedexx** [comment]
@terw-dan: The 404 error you get is fixed in #198

**Comment by atimmer** [comment]
👍🏻

**Pull request merged**
