### PR TITLE
Switch to last version of plugin-grunt-tasks

### PR DESCRIPTION
**Pull request by jdevalk**
## Summary

This PR can be summarized in the following changelog entry:

*  None needed.

## Relevant technical choices:

* Moves the entire repo to the latest version of plugin grunt tasks.

### CODE REVIEW

**Comment by IreneStr** [comment]
For test instructions, see https://github.com/Yoast/wordpress-seo/pull/13133

**Comment by igorschoester** [comment]
Acceptance 🚧 

- With the removing of the `.min.js` file there is a problem:
Looking at the release script we use (`wiki/.release.sh`) there is no JS build being done for this repo.
2 possible solutions:
  - Fix this repo to also use the `grunt release` and `grunt artifact` (the latter is already there under `create:artifact` I think). Then adapt the `wiki` repo to reflect this.
  - Keep the minified JS file in this repo. Having to remember committing it every time it changed (does not happen often).

- `build:js` (and thus also `build`) runs `uglify:js` twice.

- `build:i18n` ✅

**Comment by IreneStr** [comment]
We've decided to go for
> Keep the minified JS file in this repo. Having to remember committing it every time it changed (does not happen often).

**Comment by igorschoester** [comment]
### Done
- Added the minified JS file back.
- Upgraded `grunt-plugin-tasks` to `1.3.1`.
- Replaced `grunt check` with the new variant from `grunt-plugin-tasks`. Using `eslint` instead of `jshint` and `jscs`. Changing errors to warnings in the configuration instead of fixing them for `admin-page.js`.

### Unable to fix
The double execution of the `uglify` task when running `grunt build:js` or `grunt build`. I'm thinking it is caused by the alias only having a single task, but don't know how to fix it or why it is short from adding a dummy task.

**Comment by IreneStr** [comment]
CR 👍 
I've fixed all autofixable eslint warnings, and removed their types from .eslintrc. Now there are only 3 (camelcase-related) warnings left instead of 42.

**Comment by IreneStr** [comment]
Acceptance:
- ✅ `grunt build:i18n`
- ✅ `grunt build:js`
- ❌ `grunt build`
    - ✅ LTR languages
    - ❌ RTL languages: It's looking for minified rtl.min files which don't exist:
Schermafbeelding 2019-07-03 om 10 57 38

- ❌ `grunt release`
    - ✅ LTR languages
    - ❌ RTL languages: It's looking for minified rtl.min files which don't exist:
Schermafbeelding 2019-07-03 om 10 58 37

**Comment by igorschoester** [comment]
The RTL styles are from `wordpress-seo`. This repo does not have any CSS.
Did have to add the `developmentBuild` variable that I introduced in the `grunt-plugin-tasks` repo.

Please acceptance test first while using `yarn link`:
- Pull the `grunt-plugin-tasks` repo somewhere.
- Switch to the `add-min-in-rtlcss` branch.
- Let yarn know its available: `yarn link`.
- Go to this branch and link the `grunt-plugin-tasks` repo: `yarn link "@yoast/grunt-plugin-tasks"`.

If/when it succeeds:
- Release `grunt-plugin-tasks`.
- Bump it in this PR.
- Small test again?
- Merge!

**Comment by IreneStr** [comment]
CR 👍

**Comment by Xyfi** [comment]
Acceptance 🚧 

The task `grunt compress:artifact` fails. But I was able to run the `./create_beta` script. So this requires some investigation.

```
Verifying property compress.artifactFiles exists in config...ERROR
>> Unable to process task.
Warning: Required config property "compress.artifactFiles" missing. Use --force to continue.

Aborted due to warnings.
```

**Comment by Xyfi** [comment]
Acceptance 👍

**Comment by IreneStr** [comment]
Acceptance 👍 `artifact`, `build` and `release` all result in a fully functioning plugin.

**Pull request merged**
