### PR TITLE
Better alignments and accessibility.

### LINKED ISSUE #237: Settings page: buttons alignment
See https://github.com/Yoast/wordpress-seo/issues/5213

Reviewing all the form controls and "buttons" alignments as done for Yoast SEO. In the settings page, 3 buttons are a bit misaligned. Instead of trying to adjust the CSS, I'd propose to make them look like links because... they're links :) Any suggestion for a better wording very welcome, especially to avoid the word "here".

screen shot 2016-07-21 at 13 08 27

### PR DESCRIPTION
**Pull request by afercia**
Fixes #237 

For now this PR just changes the buttons to make them look like links because they're links. Also, makes a small change to a string, and improves a bit the spacing between the sections. Needs some good idea for a better wording to avoid the word "here" :)

### CODE REVIEW

**Comment by afercia** [comment]
Refactored a few things:

- simplified links
- added one heading
- added missing labels for checkboxes in the metabox tab
- added fieldsets (hidden) to checkboxes groups
- added translators comments
- language: "News Sitemap" instead of "XML News Sitemap", users should not be required to know what "XML" is. Also, in some places (e.g. in the "Post Types to include" heading it is already just "News Sitemap")
- language: "Editors' Picks" instead of "Editors' Pick"

**Comment by afercia** [comment]
Screenshots of the new simplified  links:

screen shot 2016-07-29 at 11 32 01

screen shot 2016-07-29 at 11 34 44

**Comment by moorscode** [comment]
CR Done 👍
Please fix the merge conflict, thanks!

**Comment by afercia** [comment]
Merged.

**Comment by afercia** [comment]
Conflicts after recent https://github.com/Yoast/wpseo-news/commit/89c4e0d0eccc6c1d3acb6f5141568626f5bcb2dc

**Comment by terw-dan** [comment]
Acceptance :+1:

**Pull request merged**
