### PR TITLE
Documentation: various fixes

### PR DESCRIPTION
**Pull request by jrfnl**
## Summary
This PR can be summarized in the following changelog entry:
_N/A_

## Relevant technical choices:
* No functional changes.

Fix up the documentation. Please see the individual commits for more detail.

## Test instructions
_N/A_

### CODE REVIEW

**Comment by jrfnl** [comment]
@dutchmartin I noticed the merging of trunk - shall I rebase the branch instead ? A quick look at the merge commit tells me that some of the fixes in this PR have been undone by the merging of trunk and that's not really the intention, I presume.

**Comment by jrfnl** [comment]
Rebased

**Comment by dutchmartin** [comment]
@jrfnl I tried to do it myself, but the next time I will first ask you about it. sorry.

**Comment by jrfnl** [comment]
@dutchmartin No worries and yes, pinging me is best in these cases.

**Pull request merged**
