### PR TITLE
Only use selected post types for editors pick [Finishes #80892074]

### LINKED ISSUE #92: Slow queries in news sitemap
For the newssitemaps and editors pick there are long queries. It look likes this is in the wp meta query. This should be optimized.

### PR DESCRIPTION
**Pull request by Petervw**
Fixes #92

### CODE REVIEW

**Comment by andizer** [comment]
This fixes only the editors pick part of issue #92. But the sitemap part itself won't be fixed. Maybe remove the fixes ... to prevent issue being closed.

**Comment by Petervw** [comment]
In the news sitemaps the post_types are already added if I'm right.

https://github.com/Yoast/wpseo-news/blob/trunk/classes/class-sitemap.php#L283

**Comment by andizer** [comment]
Code review 1 done.

**Comment by Petervw** [comment]
@andizer could you do a code review? :)

**Pull request merged**
